# Generated by Django 5.1.4 on 2025-01-03 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
