# Generated by Django 5.1.4 on 2025-01-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0010_rename_price_difference_productvariant_additional_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.PositiveIntegerField(),
        ),
    ]
