# Generated by Django 5.1.4 on 2025-01-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0014_productoffer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoffer',
            old_name='name',
            new_name='offer_name',
        ),
        migrations.RemoveField(
            model_name='productoffer',
            name='product',
        ),
        migrations.AddField(
            model_name='productoffer',
            name='criteria',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='products',
            field=models.ManyToManyField(related_name='offers', to='admin_app.product'),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='discount_percentage',
            field=models.PositiveIntegerField(),
        ),
    ]
