# Generated by Django 5.1.4 on 2025-01-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0017_salesreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_offers',
            field=models.ManyToManyField(blank=True, related_name='offered_products', to='admin_app.offer'),
        ),
    ]
