# Generated by Django 5.1.4 on 2025-01-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0021_coupon_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='variant_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
