# Generated by Django 5.1.4 on 2025-01-24 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0022_productvariant_variant_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='variant_price',
            new_name='price',
        ),
    ]
