# Generated by Django 5.1.4 on 2025-01-24 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0023_rename_variant_price_productvariant_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='price',
        ),
    ]
