# Generated by Django 5.1.4 on 2025-02-04 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0027_productvariant_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='name',
        ),
    ]
