# Generated by Django 5.1.4 on 2025-02-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0029_offer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
