# Generated by Django 5.1.4 on 2025-02-05 08:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0032_alter_offer_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
