# Generated by Django 5.1.4 on 2025-02-05 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0033_alter_offer_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 7, 8, 7, 32, 834980, tzinfo=datetime.timezone.utc)),
        ),
    ]
