# Generated by Django 5.1.4 on 2025-02-10 10:12

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0047_alter_offer_end_date_alter_referral_referral_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='offer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='offer',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 12, 10, 11, 58, 637102, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default='491C5B7473', max_length=10, unique=True),
        ),
    ]
