# Generated by Django 5.1.4 on 2025-02-10 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0048_alter_offer_options_offer_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 12, 11, 36, 51, 187376, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default='93AC3ADEA4', max_length=10, unique=True),
        ),
    ]
