# Generated by Django 5.1.4 on 2026-04-05 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0049_alter_offer_end_date_alter_referral_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 5, 17, 17, 49, 708419, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default='5DF0058E49', max_length=10, unique=True),
        ),
    ]
