# Generated by Django 5.1.4 on 2024-12-26 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_remove_customuser_phonenumber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
