# Generated by Django 5.1.4 on 2025-01-03 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_alter_order_addresses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='addresses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.address'),
        ),
    ]
