# Generated by Django 5.1.4 on 2025-01-04 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0016_order_address_alter_address_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
