# Generated by Django 5.1.4 on 2025-01-06 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0009_alter_product_brand'),
        ('user_app', '0031_userprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_app.product'),
        ),
    ]
