# Generated by Django 5.1.4 on 2025-01-06 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0033_alter_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
