# Generated by Django 5.1.4 on 2025-01-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0038_orderreturn_transaction_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default='38445975544004', max_length=14, unique=True),
        ),
    ]
