# Generated by Django 5.1.4 on 2025-01-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0043_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_update_due',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
