# Generated by Django 5.1.4 on 2025-01-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0044_order_return_update_due'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='return_update_due',
            new_name='return_requested_at',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Return Pending', 'Return Pending'), ('Return Accepted', 'Return Accepted')], default='Pending', max_length=20),
        ),
    ]
