# Generated by Django 5.1.4 on 2025-01-16 10:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0012_brand_is_active'),
        ('user_app', '0045_rename_return_update_due_order_return_requested_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'product')},
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='variant',
        ),
    ]
