# Generated by Django 5.1.4 on 2025-01-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0020_category_discount_percentage_product_discount_price_and_more'),
        ('user_app', '0057_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupons',
            field=models.ManyToManyField(blank=True, related_name='used_orders', to='admin_app.coupon'),
        ),
    ]
