# Generated by Django 5.1.4 on 2025-02-04 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0027_productvariant_name'),
        ('user_app', '0067_paymentfailed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.productvariant'),
        ),
        migrations.DeleteModel(
            name='PaymentFailed',
        ),
    ]
