# Generated by Django 5.1.4 on 2025-02-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0069_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default='DB22D84F7E', max_length=10, unique=True),
        ),
    ]
