# Generated by Django 5.1.4 on 2025-02-05 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0075_alter_referral_referral_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Referral',
        ),
    ]
