# Generated by Django 5.1.4 on 2025-02-07 15:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0078_remove_orderitem_return_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderreturn',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='return_proofs/'),
        ),
        migrations.AddField(
            model_name='orderreturn',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.orderitem'),
        ),
        migrations.AddField(
            model_name='orderreturn',
            name='return_requested_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='orderreturn',
            name='status',
            field=models.CharField(default='Return Pending', max_length=20),
        ),
    ]
