# Generated by Django 5.1.4 on 2025-02-08 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0082_alter_orderitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='status',
        ),
    ]
