# Generated by Django 5.1.4 on 2025-02-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0085_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_refunded',
            field=models.BooleanField(default=False),
        ),
    ]
