# Generated by Django 5.1.4 on 2025-01-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_remove_userprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
