# Generated by Django 5.1.4 on 2025-01-03 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_remove_order_address_remove_order_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='addresses',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_app.address'),
        ),
    ]
