# Generated by Django 5.1.4 on 2025-01-03 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0011_alter_order_addresses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='addresses',
            new_name='address',
        ),
    ]
