# Generated by Django 5.1.4 on 2025-01-03 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0014_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
