# Generated by Django 5.1.4 on 2025-01-04 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0018_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
