# Generated by Django 5.1.4 on 2025-01-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0039_alter_transaction_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default='79531851547593', max_length=14, unique=True),
        ),
    ]
