# Generated by Django 5.1.4 on 2025-01-16 10:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0046_alter_wishlist_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='added_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
