# Generated by Django 5.1.4 on 2025-01-18 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0052_order_discount_percentage_order_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 1, 18, 16, 55, 46, 189123, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
