# Generated by Django 5.1.4 on 2025-01-20 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0020_category_discount_percentage_product_discount_price_and_more'),
        ('user_app', '0054_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.productvariant'),
        ),
    ]
