# Generated by Django 5.1.4 on 2025-01-21 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0020_category_discount_percentage_product_discount_price_and_more'),
        ('user_app', '0055_cart_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.offer'),
        ),
    ]
