# Generated by Django 5.1.4 on 2025-01-28 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0060_order_payment_id_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_refunded',
            field=models.BooleanField(default=False),
        ),
    ]
