# Generated by Django 5.1.4 on 2025-01-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0063_order_delivery_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Return Pending', 'Return Pending'), ('Return Accepted', 'Return Accepted'), ('Paid', 'Paid'), ('failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
