# Generated by Django 5.1.4 on 2025-02-01 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0064_order_payment_attempts_order_payment_failed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
