# Generated by Django 5.1.4 on 2025-02-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0070_alter_referral_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default='9F3CD55804', max_length=10, unique=True),
        ),
    ]
