# Generated by Django 5.1.4 on 2025-02-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0079_order_delivered_at_orderreturn_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='returned_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderreturn',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderreturn',
            name='return_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
