# Generated by Django 5.1.4 on 2025-02-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0080_orderitem_returned_quantity_orderreturn_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Return Pending', 'Return Pending'), ('Return Accepted', 'Return Accepted')], default='Delivered', max_length=20),
        ),
    ]
