# Generated by Django 5.1.4 on 2025-02-08 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0083_remove_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderreturn',
            name='order_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderreturn', to='user_app.orderitem'),
        ),
        migrations.AlterField(
            model_name='orderreturn',
            name='status',
            field=models.CharField(choices=[('Return Pending', 'Return Pending'), ('Return Accepted', 'Return Accepted'), ('Return Rejected', 'Return Rejected')], default='Return Pending', max_length=20),
        ),
    ]
