# Generated by Django 5.1.4 on 2025-02-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0084_alter_orderreturn_order_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Return Pending', 'Return Pending'), ('Return Accepted', 'Return Accepted'), ('Paid', 'Paid'), ('Payment Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
