# Generated by Django 5.1.4 on 2024-12-26 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='email',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='product',
            name='password',
        ),
        migrations.RemoveField(
            model_name='product',
            name='username',
        ),
    ]
