# Generated by Django 5.1.4 on 2025-01-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_variant',
            field=models.BooleanField(default=False),
        ),
    ]
