# Generated by Django 5.1.4 on 2025-01-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0009_alter_product_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='price_difference',
            new_name='additional_price',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='name',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
