# Generated by Django 5.1.4 on 2025-01-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0015_rename_name_productoffer_offer_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('offer_type', models.CharField(choices=[('product', 'Product Offer'), ('category', 'Category Offer'), ('referral', 'Referral Offer')], max_length=20)),
                ('referral_code', models.CharField(blank=True, max_length=255, null=True)),
                ('categories', models.ManyToManyField(blank=True, to='admin_app.category')),
                ('products', models.ManyToManyField(blank=True, to='admin_app.product')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductOffer',
        ),
    ]
