# Generated by Django 5.1.4 on 2025-02-03 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0025_ledgerentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LedgerEntry',
        ),
    ]
