# Generated by Django 5.1.4 on 2025-02-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0026_delete_ledgerentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
