# Generated by Django 5.1.4 on 2025-02-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0030_offer_is_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
