# Generated by Django 5.1.4 on 2025-02-08 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0041_alter_offer_end_date_alter_referral_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 10, 6, 27, 21, 543192, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default='AF408EA65A', max_length=10, unique=True),
        ),
    ]
