# Generated by Django 5.1.4 on 2025-02-09 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0044_alter_offer_end_date_alter_referral_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 11, 5, 29, 4, 458107, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(default='FFF8CF41F0', max_length=10, unique=True),
        ),
    ]
